name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pwd
      run: pwd && ls -l
    - name: mkdir build
      run: mkdir -p build/
    - name: build
      run: cmake .. && make && ls -l
      working-directory: ./build/
    - name: run test
      run: ls -l && ./TestSample1
      working-directory: ./build/test