name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pwd
      run: pwd && ls -l
    - name: mkdir build
      run: mkdir -p build/
    - name: prereqs
      run: ./prereqs.sh
    - name: build
      run: ./build.sh
    - name: test
      run: ./test.sh
